# Generated by Django 4.2.16 on 2024-12-27 22:20

from django.db import migrations, models
import store.utility


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_payment_aproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.utility.dynamic_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.utility.dynamic_upload_path),
        ),
    ]
