# Generated by Django 4.2.16 on 2025-01-04 14:21

from django.db import migrations, models
import store.utility


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_composition_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.utility.dynamic_upload_path),
        ),
    ]
