# Generated by Django 4.2.16 on 2024-12-27 22:35

from django.db import migrations, models
import store.utility


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_banner_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=store.utility.dynamic_upload_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_output',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoric',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoric',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'category', 'product_type'), name='unique_product'),
        ),
    ]
