# Generated by Django 4.2.16 on 2024-12-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_banner_image_alter_banner_link_output_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemstock',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_itemstock'),
        ),
    ]
